apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
spec:
  template:
    spec:
      containers:
      - name: training
        image: gcr.io/$PROJECT_ID/training-image:latest
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: model-volume
          mountPath: /models
        env:
        - name: BATCH_SIZE
          value: "64"
        - name: EPOCHS
          value: "3"  # Reduced for faster training
        - name: LEARNING_RATE
          value: "0.001"
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-storage-pvc
      restartPolicy: Never
  backoffLimit: 2
  